Metro dr fix
dell/PyU4V pull request #108
Opened 2020-12-09 12:01 UTC by rawstorage

ci will be switched over to this branch for few runs to ensure nothing is broken, small fix and added option to metro dr

2020-12-09 12:36 UTC, MichaelMcAleer commented
Fixes issue https://github.com/dell/PyU4V/issues/105

2020-12-10 15:56 UTC, MichaelMcAleer commented
CI test fixes have been commited to this pull request to save another update later. Tests now account for scenarios of 8 or 9 health checks and also where IP interfaces may not be configured in an environment.

2020-12-11 10:32 UTC, MichaelMcAleer requested changes
Functional code looks fine, needs associated unit tests and CI tests before approval

2020-12-11 14:59 UTC, MichaelMcAleer commented
Pull request has been updated to include fix for default REST header application type.

This pull request makes the following changes:
- Fix for metro_dr delete function
- Fix for metro_dr added recover option
- Fix for CI tests:
    - PyU4V.tests.ci_tests.test_pyu4v_ci_system.CITestSystem._test_get_health_check_details
    - PyU4V.tests.ci_tests.test_pyu4v_ci_system.CITestSystem.test_get_ip_interface_list
    - PyU4V.tests.ci_tests.test_pyu4v_ci_system.CITestSystem.test_get_ip_interface
- Added Force Option to metro dr restore
- Application-Type header is now set by default to 'PyU4V-{version}'

2020-12-11 15:27 UTC, helenwalsh approved these changes

2020-12-11 15:29 UTC, MichaelMcAleer requested changes
Just the one fix needed Paul and it'll just make pep8 run clean. If CI runs cleanly over the weekend ill +1 on Monday, everything else looks fine.

2020-12-11 15:29 UTC, MichaelMcAleer commented on PyU4V/tests/unit_tests/test_pyu4v_metro_dr.py
> +            environment_name='PyU4V')
Missing indent, pep8 will fail

2020-12-14 15:20 UTC, MichaelMcAleer approved these changes

2020-12-14 16:29 UTC, MichaelMcAleer commented
CI has run cleanly, merging

2020-12-14 16:29 UTC, merged