Add emulation_type parameter to storage group and volume creation function
dell/PyU4V pull request #144
Opened 2022-01-05 04:30 UTC by travatine

Add 'emulation_type' parameter to allow creation of 'mainframe' CKD storage groups and 'CKD' volumes.
The 'deprecated' versions of 'create_' functions have not been updated as they are being removed in a future version
This fixes dell#143 .

2022-01-05 09:19 UTC, rawstorage commented
Hi Travis, thankyou for this commit, we will review and test for merge into future release.

2022-01-05 10:16 UTC, helenwalsh requested changes
First of all thank you so much for this submission.

All looks good but I notice that one or two places could break pep8.  These are formatting, style changes only.

$ tox -e pep

Also it may be no harm to add a unit test.  Something like 'test_create_storage_group_ckd' and 'test_modify_storage_group_ckd'  These would be added to the following file. 
There are several examples you can follow. PyU4V/PyU4V/tests/unit_tests/test_pyu4v_provisioning.py

All details can be found in https://pyu4v.readthedocs.io/en/latest/contribute.html

Thanks again
Helen

2022-01-06 05:12 UTC, travatine commented
Hi,

Thanks, I've fixed the incorrect whitespace and added 5 new unit tests.

After running the tests (on ubuntu 20,04 with Python 3.8 got these results:
``` 
======
Totals
======
Ran: 772 tests in 9.0185 sec.
 - Passed: 772
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 0
```

2022-01-07 12:44 UTC, rawstorage approved these changes
Approved for merge

2022-01-10 03:53 UTC, travatine commented
Hi @rawstorage ,
I've added some additional unit tests.

2022-02-03 12:27 UTC, helenwalsh commented
closed in pull request 148.

2022-02-03 12:27 UTC, closed without merging