31/logger-fix
dell/PyU4V pull request #62
Opened 2019-09-12 13:26 UTC by MichaelMcAleer

When FileHandler is loaded by logging.fileConfig() it is throwing an exception which results in NullHandler always being set. This fix changes the .conf setting in section [handler_filehandler] from class=FileHandler to class=handlers.RotatingFileHandler and sets the 'add' flag to the args.

2019-09-12 13:30 UTC, helenwalsh requested changes

2019-09-12 13:30 UTC, helenwalsh commented on PyU4V.conf.example
> +class=handlers.RotatingFileHandler
fileHandler must also be added to the list of handlers also

[handlers]
keys=consoleHandler,fileHandler

2019-09-12 13:34 UTC, MichaelMcAleer commented on PyU4V.conf.example
> +class=handlers.RotatingFileHandler
This is resolved in the latest commit

2019-09-24 12:06 UTC, rawstorage approved these changes

2019-09-24 12:36 UTC, closed without merging