Generating read the docs for 3.1.7
dell/PyU4V pull request #76
Opened 2019-11-26 16:04 UTC by helenwalsh

1.  Including openstack migrate docstrings
2.  Changing style to sphinx_rtd_theme
3.  Updating the README
4.  New Tools section for OpenStack migrate in the readthedocs

2019-11-26 16:32 UTC, rawstorage approved these changes
docs opening and going to the correct locations on my laptop.  Looks good

2019-11-26 17:02 UTC, MichaelMcAleer requested changes
Some small changes in there, everything else looks fine had a good look through the docs in the browser

2019-11-26 17:02 UTC, MichaelMcAleer commented on README.rst
> +    $ pip install PyU4V==9.1.0.0
This needs changed to 3.1.7

2019-11-26 17:02 UTC, MichaelMcAleer commented on README.rst
> -
In the coding conventions section above will you wrap any code with `` `` so it is consistent with the rest of the readme?

2019-11-26 17:02 UTC, MichaelMcAleer commented on docs/index.rst
Remove 'Indices and Tables' as a title and ref: 'search', the indices title generates a menu option which isn't desirable because it doesnt lead anywhere meaningful. The search link is broken also so will need to be removed.

I had to do this throughout the pages in the 9.1 read the docs but it is worth it for the better user experience.

2019-11-27 09:04 UTC, MichaelMcAleer commented on docs/index.rst
'Indices & Tables' is still appearing in the menu on the left of the read the docs

2019-11-27 09:05 UTC, MichaelMcAleer commented on README.rst
> -
This bit was missed in the last commit, things like .format() and :returns: should be ``.format()`` and ``:returns:``

2019-11-27 10:51 UTC, MichaelMcAleer approved these changes

2019-11-27 10:53 UTC, merged